import { readFile, writeFile, readdir, mkdir, rename } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { format, resolveConfig } from 'prettier';
import { checkCorpus } from './corpus-checks.mjs';
import { coverageReport } from './corpus-coverage.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const dataRoot = path.join(root, 'data');
const ajv = new Ajv({ allErrors: true, strictTypes: false, strictRequired: false });
addFormats(ajv);
const readJson = async file => JSON.parse(await readFile(file, 'utf8'));
const validators = new Map();
async function validateFile(file, schemaName) {
  if (!validators.has(schemaName))
    validators.set(
      schemaName,
      ajv.compile(await readJson(path.join(root, 'schema', `${schemaName}.schema.json`))),
    );
  const value = await readJson(file);
  const validate = validators.get(schemaName);
  if (!validate(value))
    throw new Error(
      `${path.relative(root, file)}: ${ajv.errorsText(validate.errors, { separator: '\n' })}`,
    );
  return value;
}
function resolveData(relative) {
  const full = path.resolve(dataRoot, relative);
  if (!full.startsWith(dataRoot + path.sep) || !relative.endsWith('.json'))
    throw new Error(`Unsafe corpus path: ${relative}`);
  return full;
}
const manifest = await validateFile(path.join(dataRoot, 'manifest.json'), 'manifest');
const { sources } = await validateFile(resolveData(manifest.sourceFile), 'sources');
const citations = [];
for (const file of manifest.citationFiles)
  citations.push(...(await validateFile(resolveData(file), 'citations')).citations);
const records = [];
for (const file of manifest.recordFiles)
  records.push(await validateFile(resolveData(file), 'record'));
const listedFiles = new Set([...manifest.recordFiles, ...manifest.citationFiles]);
for (const directory of [
  'trigrams',
  'hexagrams',
  'terms',
  'casting',
  'liuyao',
  'lessons',
  'citations',
]) {
  const entries = await readdir(path.join(dataRoot, directory), { withFileTypes: true }).catch(
    error => {
      if (error.code === 'ENOENT') return [];
      throw error;
    },
  );
  for (const entry of entries)
    if (entry.name.endsWith('.json') && !listedFiles.has(`${directory}/${entry.name}`))
      throw new Error(`Unlisted authored JSON: ${directory}/${entry.name}`);
}
const legacy = await readJson(path.join(dataRoot, 'legacy/catalog.json'));
if (legacy.reviewStatus !== 'unaudited')
  throw new Error('Compatibility snapshot must remain explicitly unaudited');
const checked = checkCorpus({ manifest, sources, citations, records, legacy });
if (process.argv.includes('--check-books')) {
  for (const source of sources)
    for (const edition of source.editions) {
      const file = path.resolve(root, '../..', edition.localInputPath);
      const hash = createHash('sha256')
        .update(await readFile(file))
        .digest('hex');
      if (hash !== edition.sha256)
        throw new Error(`${edition.id}: supplied PDF fingerprint changed`);
    }
}
const report = coverageReport({ manifest, records, citations, legacy, checked });
await saveGenerated('reports/coverage.json', JSON.stringify(report));
const imports = manifest.recordFiles.map(
  (file, i) => `import record${i} from '../data/${file}' with { type: 'json' };`,
);
const generated =
  [
    '// Generated by scripts/validate-corpus.mjs from data/manifest.json. Do not edit.',
    "import type { BookRecord, BookCitation, BookSource, BookManifest } from './book-schema.js';",
    "import manifest from '../data/manifest.json' with { type: 'json' };",
    `import sources from '../data/${manifest.sourceFile}' with { type: 'json' };`,
    ...manifest.citationFiles.map(
      (file, i) => `import citations${i} from '../data/${file}' with { type: 'json' };`,
    ),
    ...imports,
    `export const BOOK_RECORDS = [${manifest.recordFiles.map((_, i) => `record${i}`).join(', ')}] as unknown as readonly BookRecord[];`,
    `export const BOOK_CITATIONS = [${manifest.citationFiles.map((_, i) => `...citations${i}.citations`).join(', ')}] as readonly BookCitation[];`,
    'export const BOOK_SOURCES = sources.sources as readonly BookSource[];',
    'export const BOOK_MANIFEST = manifest as BookManifest;',
  ].join('\n') + '\n';
await saveGenerated('src/book-data.generated.ts', generated);
console.log(
  `Corpus valid: ${records.length} records, ${report.claims.total} claims, ${citations.length} citations; ${report.hexagrams.reviewed}/64 quẻ, ${report.lines.reviewedPositions}/384 line positions.`,
);
console.log(
  `Coverage: packages/knowledge/reports/coverage.json. Source fidelity requires passage review; schema success does not certify meaning.`,
);

async function saveGenerated(relative, content) {
  const file = path.join(root, relative);
  const formatted = await format(content, { ...(await resolveConfig(file)), filepath: file });
  const previous = await readFile(file, 'utf8').catch(error => {
    if (error.code === 'ENOENT') return null;
    throw error;
  });
  if (previous === formatted) return;
  if (process.argv.includes('--check'))
    throw new Error(`Stale generated corpus output: ${relative}`);
  await mkdir(path.dirname(file), { recursive: true });
  const temporary = `${file}.${process.pid}.tmp`;
  await writeFile(temporary, formatted);
  await rename(temporary, file);
}
