// Generated by scripts/validate-corpus.mjs. Do not edit.
import type { BookCitation } from './book-schema.js';
import type {
  BookRecordVersioned,
  ReleasedBookManifest,
  ReleasedBookSource,
} from './book-schema-v2.js';
import release from './book-release.generated.json' with { type: 'json' };
export const BOOK_RECORDS = release.records as unknown as readonly BookRecordVersioned[];
export const BOOK_CITATIONS = release.citations as unknown as readonly BookCitation[];
export const BOOK_SOURCES = release.sources as unknown as readonly ReleasedBookSource[];
export const BOOK_MANIFEST = release as unknown as ReleasedBookManifest;
export const BOOK_SNAPSHOT_IDENTITY = release.snapshotIdentity as string;
