// Generated by scripts/validate-corpus.mjs from data/manifest.json. Do not edit.
import type { BookRecord, BookCitation, BookSource, BookManifest } from './book-schema.js';
import manifest from '../data/manifest.json' with { type: 'json' };
import sources from '../data/sources.json' with { type: 'json' };
import citations0 from '../data/citations/pilot.json' with { type: 'json' };
import citations1 from '../data/citations/pilot-comparisons.json' with { type: 'json' };
import citations2 from '../data/citations/batch-two-hexagrams.json' with { type: 'json' };
import citations3 from '../data/citations/batch-two-advanced.json' with { type: 'json' };
import citations4 from '../data/citations/batch-three-hexagrams.json' with { type: 'json' };
import citations5 from '../data/citations/batch-three-advanced.json' with { type: 'json' };
import citations6 from '../data/citations/batch-four-hexagrams.json' with { type: 'json' };
import citations7 from '../data/citations/batch-four-advanced.json' with { type: 'json' };
import citations8 from '../data/citations/batch-five-hexagrams.json' with { type: 'json' };
import citations9 from '../data/citations/batch-five-advanced.json' with { type: 'json' };
import citations10 from '../data/citations/batch-six-hexagrams.json' with { type: 'json' };
import citations11 from '../data/citations/batch-six-advanced.json' with { type: 'json' };
import citations12 from '../data/citations/batch-seven-hexagrams.json' with { type: 'json' };
import citations13 from '../data/citations/batch-seven-advanced.json' with { type: 'json' };
import citations14 from '../data/citations/batch-eight-hexagrams.json' with { type: 'json' };
import citations15 from '../data/citations/batch-eight-advanced.json' with { type: 'json' };
import citations16 from '../data/citations/batch-nine-hexagrams.json' with { type: 'json' };
import record0 from '../data/trigrams/trigram-heaven.json' with { type: 'json' };
import record1 from '../data/trigrams/trigram-lake.json' with { type: 'json' };
import record2 from '../data/trigrams/trigram-fire.json' with { type: 'json' };
import record3 from '../data/trigrams/trigram-thunder.json' with { type: 'json' };
import record4 from '../data/trigrams/trigram-wind.json' with { type: 'json' };
import record5 from '../data/trigrams/trigram-water.json' with { type: 'json' };
import record6 from '../data/trigrams/trigram-mountain.json' with { type: 'json' };
import record7 from '../data/trigrams/trigram-earth.json' with { type: 'json' };
import record8 from '../data/hexagrams/hexagram-01.json' with { type: 'json' };
import record9 from '../data/hexagrams/hexagram-02.json' with { type: 'json' };
import record10 from '../data/hexagrams/hexagram-06.json' with { type: 'json' };
import record11 from '../data/hexagrams/hexagram-10.json' with { type: 'json' };
import record12 from '../data/casting/line-order.json' with { type: 'json' };
import record13 from '../data/casting/trigram-composition.json' with { type: 'json' };
import record14 from '../data/casting/moving-lines.json' with { type: 'json' };
import record15 from '../data/casting/three-coins.json' with { type: 'json' };
import record16 from '../data/casting/tung-to-ly.json' with { type: 'json' };
import record17 from '../data/liuyao/branch-elements.json' with { type: 'json' };
import record18 from '../data/liuyao/five-element-cycles.json' with { type: 'json' };
import record19 from '../data/liuyao/six-relatives.json' with { type: 'json' };
import record20 from '../data/liuyao/na-jia.json' with { type: 'json' };
import record21 from '../data/liuyao/palaces-and-markers.json' with { type: 'json' };
import record22 from '../data/terms/term-trigram.json' with { type: 'json' };
import record23 from '../data/terms/term-lower-trigram.json' with { type: 'json' };
import record24 from '../data/terms/term-upper-trigram.json' with { type: 'json' };
import record25 from '../data/terms/term-line-position.json' with { type: 'json' };
import record26 from '../data/terms/term-polarity.json' with { type: 'json' };
import record27 from '../data/terms/term-yin.json' with { type: 'json' };
import record28 from '../data/terms/term-yang.json' with { type: 'json' };
import record29 from '../data/terms/term-moving-line.json' with { type: 'json' };
import record30 from '../data/terms/term-palace.json' with { type: 'json' };
import record31 from '../data/terms/term-palace-element.json' with { type: 'json' };
import record32 from '../data/terms/term-shi-line.json' with { type: 'json' };
import record33 from '../data/terms/term-ying-line.json' with { type: 'json' };
import record34 from '../data/terms/term-na-jia.json' with { type: 'json' };
import record35 from '../data/terms/term-heavenly-stem.json' with { type: 'json' };
import record36 from '../data/terms/term-earthly-branch.json' with { type: 'json' };
import record37 from '../data/terms/term-five-elements.json' with { type: 'json' };
import record38 from '../data/terms/term-six-relative.json' with { type: 'json' };
import record39 from '../data/terms/term-relative-sibling.json' with { type: 'json' };
import record40 from '../data/terms/term-relative-child.json' with { type: 'json' };
import record41 from '../data/terms/term-relative-wealth.json' with { type: 'json' };
import record42 from '../data/terms/term-relative-official-ghost.json' with { type: 'json' };
import record43 from '../data/terms/term-relative-parent.json' with { type: 'json' };
import record44 from '../data/terms/term-element-generation.json' with { type: 'json' };
import record45 from '../data/terms/term-element-control.json' with { type: 'json' };
import record46 from '../data/terms/term-element-metal.json' with { type: 'json' };
import record47 from '../data/terms/term-element-wood.json' with { type: 'json' };
import record48 from '../data/terms/term-element-water.json' with { type: 'json' };
import record49 from '../data/terms/term-element-fire.json' with { type: 'json' };
import record50 from '../data/terms/term-element-earth.json' with { type: 'json' };
import record51 from '../data/terms/term-stem-jia.json' with { type: 'json' };
import record52 from '../data/terms/term-stem-yi.json' with { type: 'json' };
import record53 from '../data/terms/term-stem-bing.json' with { type: 'json' };
import record54 from '../data/terms/term-stem-ding.json' with { type: 'json' };
import record55 from '../data/terms/term-stem-wu.json' with { type: 'json' };
import record56 from '../data/terms/term-stem-ji.json' with { type: 'json' };
import record57 from '../data/terms/term-stem-geng.json' with { type: 'json' };
import record58 from '../data/terms/term-stem-xin.json' with { type: 'json' };
import record59 from '../data/terms/term-stem-ren.json' with { type: 'json' };
import record60 from '../data/terms/term-stem-gui.json' with { type: 'json' };
import record61 from '../data/terms/term-branch-zi.json' with { type: 'json' };
import record62 from '../data/terms/term-branch-chou.json' with { type: 'json' };
import record63 from '../data/terms/term-branch-yin.json' with { type: 'json' };
import record64 from '../data/terms/term-branch-mao.json' with { type: 'json' };
import record65 from '../data/terms/term-branch-chen.json' with { type: 'json' };
import record66 from '../data/terms/term-branch-si.json' with { type: 'json' };
import record67 from '../data/terms/term-branch-wu.json' with { type: 'json' };
import record68 from '../data/terms/term-branch-wei.json' with { type: 'json' };
import record69 from '../data/terms/term-branch-shen.json' with { type: 'json' };
import record70 from '../data/terms/term-branch-you.json' with { type: 'json' };
import record71 from '../data/terms/term-branch-xu.json' with { type: 'json' };
import record72 from '../data/terms/term-branch-hai.json' with { type: 'json' };
import record73 from '../data/hexagrams/hexagram-03.json' with { type: 'json' };
import record74 from '../data/hexagrams/hexagram-04.json' with { type: 'json' };
import record75 from '../data/hexagrams/hexagram-05.json' with { type: 'json' };
import record76 from '../data/hexagrams/hexagram-07.json' with { type: 'json' };
import record77 from '../data/terms/term-useful-spirit.json' with { type: 'json' };
import record78 from '../data/terms/term-origin-spirit.json' with { type: 'json' };
import record79 from '../data/terms/term-adverse-spirit.json' with { type: 'json' };
import record80 from '../data/terms/term-enemy-spirit.json' with { type: 'json' };
import record81 from '../data/liuyao/useful-spirit-selection.json' with { type: 'json' };
import record82 from '../data/liuyao/shi-ying-as-useful-spirit.json' with { type: 'json' };
import record83 from '../data/liuyao/origin-adverse-and-enemy-spirits.json' with { type: 'json' };
import record84 from '../data/hexagrams/hexagram-08.json' with { type: 'json' };
import record85 from '../data/hexagrams/hexagram-09.json' with { type: 'json' };
import record86 from '../data/hexagrams/hexagram-11.json' with { type: 'json' };
import record87 from '../data/hexagrams/hexagram-12.json' with { type: 'json' };
import record88 from '../data/terms/term-flying-spirit.json' with { type: 'json' };
import record89 from '../data/terms/term-hidden-spirit.json' with { type: 'json' };
import record90 from '../data/terms/term-six-spirits.json' with { type: 'json' };
import record91 from '../data/terms/term-spirit-qinglong.json' with { type: 'json' };
import record92 from '../data/terms/term-spirit-zhuque.json' with { type: 'json' };
import record93 from '../data/terms/term-spirit-gouchen.json' with { type: 'json' };
import record94 from '../data/terms/term-spirit-tengshe.json' with { type: 'json' };
import record95 from '../data/terms/term-spirit-baihu.json' with { type: 'json' };
import record96 from '../data/terms/term-spirit-xuanwu.json' with { type: 'json' };
import record97 from '../data/liuyao/flying-spirit-uses.json' with { type: 'json' };
import record98 from '../data/liuyao/hidden-spirit-method.json' with { type: 'json' };
import record99 from '../data/liuyao/six-spirits-context.json' with { type: 'json' };
import record100 from '../data/hexagrams/hexagram-13.json' with { type: 'json' };
import record101 from '../data/hexagrams/hexagram-14.json' with { type: 'json' };
import record102 from '../data/hexagrams/hexagram-15.json' with { type: 'json' };
import record103 from '../data/hexagrams/hexagram-16.json' with { type: 'json' };
import record104 from '../data/terms/term-four-birthplaces.json' with { type: 'json' };
import record105 from '../data/terms/term-growth-stage.json' with { type: 'json' };
import record106 from '../data/terms/term-store-stage.json' with { type: 'json' };
import record107 from '../data/terms/term-extinction-stage.json' with { type: 'json' };
import record108 from '../data/terms/term-month-break.json' with { type: 'json' };
import record109 from '../data/terms/term-true-month-break.json' with { type: 'json' };
import record110 from '../data/terms/term-decade-empty.json' with { type: 'json' };
import record111 from '../data/terms/term-effective-empty.json' with { type: 'json' };
import record112 from '../data/terms/term-matching-day.json' with { type: 'json' };
import record113 from '../data/terms/term-leaving-decade.json' with { type: 'json' };
import record114 from '../data/liuyao/growth-store-and-extinction.json' with { type: 'json' };
import record115 from '../data/liuyao/month-break-conditions.json' with { type: 'json' };
import record116 from '../data/liuyao/decade-empty-conditions.json' with { type: 'json' };
import record117 from '../data/hexagrams/hexagram-17.json' with { type: 'json' };
import record118 from '../data/hexagrams/hexagram-18.json' with { type: 'json' };
import record119 from '../data/hexagrams/hexagram-19.json' with { type: 'json' };
import record120 from '../data/hexagrams/hexagram-20.json' with { type: 'json' };
import record121 from '../data/terms/term-reverse-chant.json' with { type: 'json' };
import record122 from '../data/terms/term-line-reverse-chant.json' with { type: 'json' };
import record123 from '../data/terms/term-repeated-chant.json' with { type: 'json' };
import record124 from '../data/liuyao/reverse-chant-context.json' with { type: 'json' };
import record125 from '../data/liuyao/repeated-chant-context.json' with { type: 'json' };
import record126 from '../data/hexagrams/hexagram-21.json' with { type: 'json' };
import record127 from '../data/hexagrams/hexagram-22.json' with { type: 'json' };
import record128 from '../data/hexagrams/hexagram-23.json' with { type: 'json' };
import record129 from '../data/hexagrams/hexagram-24.json' with { type: 'json' };
import record130 from '../data/terms/term-prosperous-supported.json' with { type: 'json' };
import record131 from '../data/terms/term-resting-confined.json' with { type: 'json' };
import record132 from '../data/terms/term-combination-control.json' with { type: 'json' };
import record133 from '../data/liuyao/seasonal-strength-context.json' with { type: 'json' };
import record134 from '../data/liuyao/combination-control-context.json' with { type: 'json' };
import record135 from '../data/hexagrams/hexagram-25.json' with { type: 'json' };
import record136 from '../data/hexagrams/hexagram-26.json' with { type: 'json' };
import record137 from '../data/hexagrams/hexagram-27.json' with { type: 'json' };
import record138 from '../data/hexagrams/hexagram-28.json' with { type: 'json' };
import record139 from '../data/terms/term-combination-meets-opposition.json' with { type: 'json' };
import record140 from '../data/terms/term-opposition-meets-combination.json' with { type: 'json' };
import record141 from '../data/terms/term-extinction-meets-generation.json' with { type: 'json' };
import record142 from '../data/terms/term-control-meets-generation.json' with { type: 'json' };
import record143 from '../data/liuyao/combination-opposition-turnarounds.json' with { type: 'json' };
import record144 from '../data/liuyao/extinction-control-support.json' with { type: 'json' };
import record145 from '../data/hexagrams/hexagram-29.json' with { type: 'json' };
import record146 from '../data/hexagrams/hexagram-30.json' with { type: 'json' };
import record147 from '../data/hexagrams/hexagram-31.json' with { type: 'json' };
import record148 from '../data/hexagrams/hexagram-32.json' with { type: 'json' };
import record149 from '../data/terms/term-advancing-spirit.json' with { type: 'json' };
import record150 from '../data/terms/term-retreating-spirit.json' with { type: 'json' };
import record151 from '../data/liuyao/advancing-retreating-spirits.json' with { type: 'json' };
import record152 from '../data/liuyao/divination-context-and-proxy-role.json' with { type: 'json' };
import record153 from '../data/hexagrams/hexagram-33.json' with { type: 'json' };
import record154 from '../data/hexagrams/hexagram-34.json' with { type: 'json' };
import record155 from '../data/hexagrams/hexagram-35.json' with { type: 'json' };
import record156 from '../data/hexagrams/hexagram-36.json' with { type: 'json' };
export const BOOK_RECORDS = [
  record0,
  record1,
  record2,
  record3,
  record4,
  record5,
  record6,
  record7,
  record8,
  record9,
  record10,
  record11,
  record12,
  record13,
  record14,
  record15,
  record16,
  record17,
  record18,
  record19,
  record20,
  record21,
  record22,
  record23,
  record24,
  record25,
  record26,
  record27,
  record28,
  record29,
  record30,
  record31,
  record32,
  record33,
  record34,
  record35,
  record36,
  record37,
  record38,
  record39,
  record40,
  record41,
  record42,
  record43,
  record44,
  record45,
  record46,
  record47,
  record48,
  record49,
  record50,
  record51,
  record52,
  record53,
  record54,
  record55,
  record56,
  record57,
  record58,
  record59,
  record60,
  record61,
  record62,
  record63,
  record64,
  record65,
  record66,
  record67,
  record68,
  record69,
  record70,
  record71,
  record72,
  record73,
  record74,
  record75,
  record76,
  record77,
  record78,
  record79,
  record80,
  record81,
  record82,
  record83,
  record84,
  record85,
  record86,
  record87,
  record88,
  record89,
  record90,
  record91,
  record92,
  record93,
  record94,
  record95,
  record96,
  record97,
  record98,
  record99,
  record100,
  record101,
  record102,
  record103,
  record104,
  record105,
  record106,
  record107,
  record108,
  record109,
  record110,
  record111,
  record112,
  record113,
  record114,
  record115,
  record116,
  record117,
  record118,
  record119,
  record120,
  record121,
  record122,
  record123,
  record124,
  record125,
  record126,
  record127,
  record128,
  record129,
  record130,
  record131,
  record132,
  record133,
  record134,
  record135,
  record136,
  record137,
  record138,
  record139,
  record140,
  record141,
  record142,
  record143,
  record144,
  record145,
  record146,
  record147,
  record148,
  record149,
  record150,
  record151,
  record152,
  record153,
  record154,
  record155,
  record156,
] as unknown as readonly BookRecord[];
export const BOOK_CITATIONS = [
  ...citations0.citations,
  ...citations1.citations,
  ...citations2.citations,
  ...citations3.citations,
  ...citations4.citations,
  ...citations5.citations,
  ...citations6.citations,
  ...citations7.citations,
  ...citations8.citations,
  ...citations9.citations,
  ...citations10.citations,
  ...citations11.citations,
  ...citations12.citations,
  ...citations13.citations,
  ...citations14.citations,
  ...citations15.citations,
  ...citations16.citations,
] as readonly BookCitation[];
export const BOOK_SOURCES = sources.sources as readonly BookSource[];
export const BOOK_MANIFEST = manifest as BookManifest;
