// Generated by scripts/validate-corpus.mjs from data/manifest.json. Do not edit.
import type { BookRecord, BookCitation, BookSource, BookManifest } from './book-schema.js';
import manifest from '../data/manifest.json' with { type: 'json' };
import sources from '../data/sources.json' with { type: 'json' };
import citations0 from '../data/citations/pilot.json' with { type: 'json' };
import citations1 from '../data/citations/pilot-comparisons.json' with { type: 'json' };
import citations2 from '../data/citations/batch-two-hexagrams.json' with { type: 'json' };
import record0 from '../data/trigrams/trigram-heaven.json' with { type: 'json' };
import record1 from '../data/trigrams/trigram-lake.json' with { type: 'json' };
import record2 from '../data/trigrams/trigram-fire.json' with { type: 'json' };
import record3 from '../data/trigrams/trigram-thunder.json' with { type: 'json' };
import record4 from '../data/trigrams/trigram-wind.json' with { type: 'json' };
import record5 from '../data/trigrams/trigram-water.json' with { type: 'json' };
import record6 from '../data/trigrams/trigram-mountain.json' with { type: 'json' };
import record7 from '../data/trigrams/trigram-earth.json' with { type: 'json' };
import record8 from '../data/hexagrams/hexagram-01.json' with { type: 'json' };
import record9 from '../data/hexagrams/hexagram-02.json' with { type: 'json' };
import record10 from '../data/hexagrams/hexagram-06.json' with { type: 'json' };
import record11 from '../data/hexagrams/hexagram-10.json' with { type: 'json' };
import record12 from '../data/casting/line-order.json' with { type: 'json' };
import record13 from '../data/casting/trigram-composition.json' with { type: 'json' };
import record14 from '../data/casting/moving-lines.json' with { type: 'json' };
import record15 from '../data/casting/three-coins.json' with { type: 'json' };
import record16 from '../data/casting/tung-to-ly.json' with { type: 'json' };
import record17 from '../data/liuyao/branch-elements.json' with { type: 'json' };
import record18 from '../data/liuyao/five-element-cycles.json' with { type: 'json' };
import record19 from '../data/liuyao/six-relatives.json' with { type: 'json' };
import record20 from '../data/liuyao/na-jia.json' with { type: 'json' };
import record21 from '../data/liuyao/palaces-and-markers.json' with { type: 'json' };
import record22 from '../data/terms/term-trigram.json' with { type: 'json' };
import record23 from '../data/terms/term-lower-trigram.json' with { type: 'json' };
import record24 from '../data/terms/term-upper-trigram.json' with { type: 'json' };
import record25 from '../data/terms/term-line-position.json' with { type: 'json' };
import record26 from '../data/terms/term-polarity.json' with { type: 'json' };
import record27 from '../data/terms/term-yin.json' with { type: 'json' };
import record28 from '../data/terms/term-yang.json' with { type: 'json' };
import record29 from '../data/terms/term-moving-line.json' with { type: 'json' };
import record30 from '../data/terms/term-palace.json' with { type: 'json' };
import record31 from '../data/terms/term-palace-element.json' with { type: 'json' };
import record32 from '../data/terms/term-shi-line.json' with { type: 'json' };
import record33 from '../data/terms/term-ying-line.json' with { type: 'json' };
import record34 from '../data/terms/term-na-jia.json' with { type: 'json' };
import record35 from '../data/terms/term-heavenly-stem.json' with { type: 'json' };
import record36 from '../data/terms/term-earthly-branch.json' with { type: 'json' };
import record37 from '../data/terms/term-five-elements.json' with { type: 'json' };
import record38 from '../data/terms/term-six-relative.json' with { type: 'json' };
import record39 from '../data/terms/term-relative-sibling.json' with { type: 'json' };
import record40 from '../data/terms/term-relative-child.json' with { type: 'json' };
import record41 from '../data/terms/term-relative-wealth.json' with { type: 'json' };
import record42 from '../data/terms/term-relative-official-ghost.json' with { type: 'json' };
import record43 from '../data/terms/term-relative-parent.json' with { type: 'json' };
import record44 from '../data/terms/term-element-generation.json' with { type: 'json' };
import record45 from '../data/terms/term-element-control.json' with { type: 'json' };
import record46 from '../data/terms/term-element-metal.json' with { type: 'json' };
import record47 from '../data/terms/term-element-wood.json' with { type: 'json' };
import record48 from '../data/terms/term-element-water.json' with { type: 'json' };
import record49 from '../data/terms/term-element-fire.json' with { type: 'json' };
import record50 from '../data/terms/term-element-earth.json' with { type: 'json' };
import record51 from '../data/terms/term-stem-jia.json' with { type: 'json' };
import record52 from '../data/terms/term-stem-yi.json' with { type: 'json' };
import record53 from '../data/terms/term-stem-bing.json' with { type: 'json' };
import record54 from '../data/terms/term-stem-ding.json' with { type: 'json' };
import record55 from '../data/terms/term-stem-wu.json' with { type: 'json' };
import record56 from '../data/terms/term-stem-ji.json' with { type: 'json' };
import record57 from '../data/terms/term-stem-geng.json' with { type: 'json' };
import record58 from '../data/terms/term-stem-xin.json' with { type: 'json' };
import record59 from '../data/terms/term-stem-ren.json' with { type: 'json' };
import record60 from '../data/terms/term-stem-gui.json' with { type: 'json' };
import record61 from '../data/terms/term-branch-zi.json' with { type: 'json' };
import record62 from '../data/terms/term-branch-chou.json' with { type: 'json' };
import record63 from '../data/terms/term-branch-yin.json' with { type: 'json' };
import record64 from '../data/terms/term-branch-mao.json' with { type: 'json' };
import record65 from '../data/terms/term-branch-chen.json' with { type: 'json' };
import record66 from '../data/terms/term-branch-si.json' with { type: 'json' };
import record67 from '../data/terms/term-branch-wu.json' with { type: 'json' };
import record68 from '../data/terms/term-branch-wei.json' with { type: 'json' };
import record69 from '../data/terms/term-branch-shen.json' with { type: 'json' };
import record70 from '../data/terms/term-branch-you.json' with { type: 'json' };
import record71 from '../data/terms/term-branch-xu.json' with { type: 'json' };
import record72 from '../data/terms/term-branch-hai.json' with { type: 'json' };
import record73 from '../data/hexagrams/hexagram-03.json' with { type: 'json' };
import record74 from '../data/hexagrams/hexagram-04.json' with { type: 'json' };
import record75 from '../data/hexagrams/hexagram-05.json' with { type: 'json' };
import record76 from '../data/hexagrams/hexagram-07.json' with { type: 'json' };
export const BOOK_RECORDS = [
  record0,
  record1,
  record2,
  record3,
  record4,
  record5,
  record6,
  record7,
  record8,
  record9,
  record10,
  record11,
  record12,
  record13,
  record14,
  record15,
  record16,
  record17,
  record18,
  record19,
  record20,
  record21,
  record22,
  record23,
  record24,
  record25,
  record26,
  record27,
  record28,
  record29,
  record30,
  record31,
  record32,
  record33,
  record34,
  record35,
  record36,
  record37,
  record38,
  record39,
  record40,
  record41,
  record42,
  record43,
  record44,
  record45,
  record46,
  record47,
  record48,
  record49,
  record50,
  record51,
  record52,
  record53,
  record54,
  record55,
  record56,
  record57,
  record58,
  record59,
  record60,
  record61,
  record62,
  record63,
  record64,
  record65,
  record66,
  record67,
  record68,
  record69,
  record70,
  record71,
  record72,
  record73,
  record74,
  record75,
  record76,
] as unknown as readonly BookRecord[];
export const BOOK_CITATIONS = [
  ...citations0.citations,
  ...citations1.citations,
  ...citations2.citations,
] as readonly BookCitation[];
export const BOOK_SOURCES = sources.sources as readonly BookSource[];
export const BOOK_MANIFEST = manifest as BookManifest;
